version: "3.9"

services:
  api:
    container_name: everyday-health-api
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "yarn migrate:up && yarn test && yarn test:e2e && yarn run start"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    container_name: everyday-health-mongodb
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
